### ISSUE TITLE
[Feature Request]: Java 8 support

### ISSUE THREAD

**Issue by devaskim** [apache/plc4x#1600]
### What would you like to happen?

Is there any plans to back port the library to Java 8?

### Programming Languages

- [X] plc4j
- [ ] plc4go
- [ ] plc4c
- [ ] plc4net

### Protocols

- [ ] AB-Ethernet
- [ ] ADS /AMS
- [ ] BACnet/IP
- [ ] CANopen
- [ ] DeltaV
- [ ] DF1
- [ ] EtherNet/IP
- [ ] Firmata
- [ ] KNXnet/IP
- [ ] Modbus
- [ ] OPC-UA
- [X] S7

**Comment by ottlukas** [comment]
Thanks for requesting Java 8 support. We understand it might be a limitation for some users.

PLC4X intentionally dropped Java 8 support to streamline development for our contributors and leverage newer features that improve the codebase's maintainability. You can see the dicussion here: [Which is the minimal Java version plc4j should support](https://github.com/apache/plc4x/discussions/1059). We did not even conisder Java 8 anymore.

Upgrading to Java 11 (LTS) or later is highly recommended for full functionality and access to the latest features.

Unfortunately, backporting PLC4X to Java 8 currently isn't feasible due to resource limitations. The community would be happy to consider backporting efforts if additional resources become available, such as a developer resource (working regulary on supporting Java 8) or sponsored development.
