### ISSUE TITLE
Is there any plan time for C 

### ISSUE THREAD

**Issue by Salitanr** [apache/plc4x#1711]
### What would you like to happen?

hi,Is there any plan time  about plc4c

### Programming Languages

- [ ] plc4j
- [ ] plc4go
- [X] plc4c
- [ ] plc4net

### Protocols

- [X] AB-Ethernet
- [X] ADS /AMS
- [X] BACnet/IP
- [X] CANopen
- [X] DeltaV
- [X] DF1
- [X] EtherNet/IP
- [X] Firmata
- [X] KNXnet/IP
- [X] Modbus
- [X] OPC-UA
- [X] S7

**Comment by chrisdutz** [comment]
There is no budget to help develop, so there is no time-plan at all. Everything will happen if somone needs it and is willing to invest the time to do it, or finance someone else to do it for him.

But you did notice, that there's already a PLC4X ... just not all drivers supported and not all features of S7 and modbus are implmented (But that generally was intentional to keep the driver simple and small)

**Comment by chrisdutz** [comment]
So if there is no feeback on either options (willing to work on it yourself or that there's budget availalbe) I think I will close this issue with the answer "No" next time I come here ;-)
