### ISSUE TITLE
[Bug]: Document case version error

### ISSUE THREAD

**Issue by ZY945** [apache/plc4x#1912]
### What happened?

I found that the release version is 0.12.0. But the branch ends with 0.12, and the document uses the version number of the branch.I hope we can unify it.
https://plc4x.apache.org/plc4x/0.12/users/getting-started/plc4j.html#_using_the_plc4j_api_directly
https://mvnrepository.com/artifact/org.apache.plc4x/plc4j-driver-s7/0.12.0
https://mvnrepository.com/artifact/org.apache.plc4x/plc4j-api/0.12.0
<img width="272" alt="image" src="https://github.com/user-attachments/assets/53da8f87-2b75-41f3-9c89-f94dcda7cf4b">
<img width="1470" alt="image" src="https://github.com/user-attachments/assets/1e4bf22a-8f21-4edb-b20d-fe063371b3c7">
<img width="1099" alt="image" src="https://github.com/user-attachments/assets/6796926f-4e82-4823-a097-e716cb78a9d4">

### Version

0.12.0

### Programming Languages

- [ ] plc4j
- [ ] plc4go
- [ ] plc4c
- [ ] plc4net

### Protocols

- [ ] AB-Ethernet
- [ ] ADS /AMS
- [ ] BACnet/IP
- [ ] CANopen
- [ ] DeltaV
- [ ] DF1
- [ ] EtherNet/IP
- [ ] Firmata
- [ ] KNXnet/IP
- [ ] Modbus
- [ ] OPC-UA
- [ ] S7

**Comment by hutcheb** [comment]
Thanks for pointing that out, I have now updated the 0.12 branch to use 0.12.0 instead, in the antora.yml file.

The website will get updated on the next successful CI run.
https://ci-builds.apache.org/blue/organizations/jenkins/PLC4X%2FPLC4X/detail/develop/

Thanks Again :)

**Comment by chrisdutz** [comment]
Well ... actually the branch name was 0.12 intentionally ... usually the branch contains all bugfix versions of a 0.12 release ... so it would usually contain 0.12.0, 0.12.1, 0.12.2 ... we're not doing that right now, but that's the normal pattern of maven git projects.

The tag should reflect a version .... because technically the rel/0.12.0 branch is in version 0.12.1-SNAPSHOT after the release.

**Comment by hutcheb** [comment]
I think it makes some sense to keep this section as 0.12 as we probably won't keep multiple minor versions of the docs on the website.
![image](https://github.com/user-attachments/assets/0008d884-e03f-4cc8-bb72-b7c7b8c1060b)
So that it doesn't change if a version 0.12.1 is ever released.

But having the 0.12.0 in the examples and docs I definitely makes sense.

I'm not sure there's a need to have a separate branch for docs for each minor release. So keeping the 0.12 docs on the rel/0.12 branch, then if a 0.12.1 is released, the website for version 0.12 would get incremented to 0.12.1 in the examples, and we wouldn't have the 0.12.0 referenced on the website anymore (Except for the release notes).
