### ISSUE TITLE
PLC4GO - Timeout during S7 Logo 8 Connection

### ISSUE THREAD

**Issue by ottlukas** [apache/plc4x#640]
Might be a user-error like in PLC4X-346 but I'm not sure. 

When connection to local Siemens LOG 8 via ConnectionString "
s7://192.168.0.3" the connection request fails after several seconds with timeout error.
 !image-2022-06-29-01-21-25-289.png! 
[.....]
 !image-2022-06-29-01-19-31-144.png!

I'm using the Go example setup. I double checked if the Logo is reachable by connecting via NodeJS lib to it & for sure I tried reconfiguring the rack/slot options. 

Happy to provide more information if needed.

Imported from Jira [PLC4X-348](https://issues.apache.org/jira/browse/PLC4X-348). Original Jira may contain additional context.
Reported by: Vormweg.

**Comment by chrisdutz** [comment]
When using a Siemens LOGO device, unfortunately Siemens didn't implement all features of the underlying protocols. When connecting to a LOGO device, the driver will try reading an SZL in order to detect the type of device ... unfortunateyl the LOGO just hangs up when receiving this request. Please be sure to add the following parameter to your conneciton-string, to make it skip this step: `?controller-type=LOGO`

We should definitely document this on in the documentation ...

**Comment by chrisdutz** [comment]
Added a NOTICE to the S7 documentation,
